# Generated by Django 3.0.7 on 2020-06-21 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatter',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
